# Generated by Django 2.1.1 on 2018-12-07 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compquiz',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='compquiz',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='CompQuiz',
        ),
    ]
