# Generated by Django 2.1.1 on 2018-12-09 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_compquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompQuizEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_started', models.DateTimeField(blank=True, null=True)),
                ('datetime_completed', models.DateTimeField(blank=True, null=True)),
                ('final_grade', models.FloatField(blank=True, null=True)),
                ('certain_comp_quiz', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Quiz')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile')),
            ],
        ),
    ]
