# Generated by Django 2.1.1 on 2018-12-09 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_compquestionentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compquestionentry',
            name='comp_quiz_entry',
        ),
        migrations.RemoveField(
            model_name='compquestionentry',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='compquestionentry',
            name='selected_answer',
        ),
        migrations.RemoveField(
            model_name='compquizentry',
            name='certain_comp_quiz',
        ),
        migrations.RemoveField(
            model_name='compquizentry',
            name='student',
        ),
        migrations.DeleteModel(
            name='CompQuestionEntry',
        ),
        migrations.DeleteModel(
            name='CompQuizEntry',
        ),
    ]
