# Generated by Django 2.1.1 on 2018-12-09 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181209_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompQuestionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CompQuizEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_started', models.DateTimeField(blank=True, null=True)),
                ('datetime_completed', models.DateTimeField(blank=True, null=True)),
                ('final_grade', models.FloatField(blank=True, null=True)),
                ('certain_comp_quiz', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.CompQuiz')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='compquestionentry',
            name='comp_quiz_entry',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.CompQuizEntry'),
        ),
        migrations.AddField(
            model_name='compquestionentry',
            name='correct_answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='correct_comp_answer', to='main.Answer'),
        ),
        migrations.AddField(
            model_name='compquestionentry',
            name='selected_answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='selected_comp_answer', to='main.Answer'),
        ),
    ]
